---
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-operator
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nvidia-gpu-operator-repository
  namespace: gpu-operator
spec:
  interval: 1m0s
  url: https://helm.ngc.nvidia.com/nvidia
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nvidia-gpu-operator-release
  namespace: gpu-operator
spec:
  interval: 1m0s
  chart:
    spec:
      chart: gpu-operator
      version: "24.6.1"
      sourceRef:
        kind: HelmRepository
        name: nvidia-gpu-operator-repository
        namespace: gpu-operator
  install:
    crds: CreateReplace
  values:
    driver:
      nvidiaDriverCRD:
        enabled: true
    toolkit:
      enabled: true
      env:
        - name: CONTAINERD_CONFIG
          value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
        - name: CONTAINERD_SOCKET
          value: /run/k3s/containerd/containerd.sock
        - name: CONTAINERD_RUNTIME_CLASS
          value: nvidia
        - name: CONTAINERD_SET_AS_DEFAULT
          value: "true"
        - name: NVIDIA_DISABLE_REQUIRE
          value: "true"