# docker-compose.yml
version: '3.8'

services:
  # TODO set up LiteLLM docker image

  # vLLM Instance 0 serving Hermes 3 8B on GPU 0
  vllm-0-hermes:
    image: vllm/vllm-openai:v0.6.3
    entrypoint: [
      "vllm", "serve", "NousResearch/Hermes-3-Llama-3.1-8B",
      "--enable-prefix-caching", "--enable-auto-tool-choice", "--enable-chunked-prefill",
      "--gpu-memory-utilization", "0.98",
      "--max-model-len", "131072",
      "--tool-call-parser", "hermes",
      "--max-num-batched-tokens", "512",
      "--max-num-seqs", "256",
      "--num-scheduler-steps", "1"
    ]
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - /ephemeral/huggingface:/root/.cache/huggingface # storage for HF cache
      - ./configs:/usr/app # configs like chat templates, vllm configs, tool parsers
    ports:
      - "8000:8000"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vllm-1-qwen25:
    image: vllm/vllm-openai:v0.6.3
    entrypoint: [
      "vllm", "serve", "Qwen/Qwen2.5-7B-Instruct",
      "--enable-prefix-caching", "--enable-auto-tool-choice", "--enable-chunked-prefill",
      "--gpu-memory-utilization", "0.98",
      "--max-model-len", "32768",
      "--tool-call-parser", "hermes",
      "--max-num-batched-tokens", "512",
      "--max-num-seqs", "256",
      "--num-scheduler-steps", "1"
    ]
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - /ephemeral/huggingface:/root/.cache/huggingface # storage for HF cache
      - ./configs:/usr/app # configs like chat templates, vllm configs, tool parsers
    ports:
      - "8001:8000"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  vllm-2-llama31:
    image: vllm/vllm-openai:v0.6.3
    entrypoint: [
      "vllm", "serve", "meta-llama/Llama-3.1-8B-Instruct",
      "--enable-prefix-caching", "--enable-auto-tool-choice", "--enable-chunked-prefill",
      "--gpu-memory-utilization", "0.98",
      "--max-model-len", "131072",
      "--tool-call-parser", "llama3_json",
      "--max-num-batched-tokens", "512",
      "--max-num-seqs", "256",
      "--num-scheduler-steps", "1",
      # custom chat template with better system prompt improves performance!
      "--chat-template", "/usr/app/chat-templates/llama_3_1.jinja"
    ]
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - /ephemeral/huggingface:/root/.cache/huggingface # storage for HF cache
      - ./configs:/usr/app # configs like chat templates, vllm configs, tool parsers
    ports:
      - "8002:8000"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  vllm-3-toolace:
    image: vllm/vllm-openai:v0.6.3
    entrypoint: [
      "vllm", "serve", "Team-ACE/ToolACE-8B",
      "--enable-prefix-caching", "--enable-auto-tool-choice", "--enable-chunked-prefill",
      "--tool-parser-plugin", "/usr/app/tool-parsers/pythonic_tool_parser.py",
      "--gpu-memory-utilization", "0.98",
      "--max-model-len", "131072",
      "--tool-call-parser", "pythonic",
      "--max-num-batched-tokens", "512",
      "--max-num-seqs", "256",
      "--num-scheduler-steps", "1",
      # custom chat template with better system prompt improves performance!
      "--chat-template", "/usr/app/chat-templates/tool_ace.jinja"
    ]
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - /ephemeral/huggingface:/root/.cache/huggingface # storage for HF cache
      - ./configs:/usr/app # configs like chat templates, vllm configs, tool parsers
    ports:
      - "8003:8000"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  # openbmb/MiniCPM3-4B
  vllm-4-minicpm3:
    image: vllm/vllm-openai:v0.6.3
    entrypoint: [
      "vllm", "serve", "openbmb/MiniCPM3-4B",
      "--enable-prefix-caching", "--enable-auto-tool-choice", "--enable-chunked-prefill",
      "--tool-parser-plugin", "/usr/app/tool-parsers/minicpm3_tool_parser.py",
      "--gpu-memory-utilization", "0.98",
      "--max-model-len", "32768",
      "--tool-call-parser", "minicpm",
      "--max-num-batched-tokens", "512",
      "--max-num-seqs", "256",
      "--num-scheduler-steps", "1",
      # custom chat template with better system prompt improves performance!
      "--chat-template", "/usr/app/chat-templates/minicpm3_4b.jinja",
      "--trust-remote-code"
    ]
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGINGFACE_TOKEN}
    volumes:
      - /ephemeral/huggingface:/root/.cache/huggingface # storage for HF cache
      - ./configs:/usr/app # configs like chat templates, vllm configs, tool parsers
    ports:
      - "8004:8000"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]


  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-blacklight:/prometheus
      # TODO add a volume to persist prometheus data
    ports:
      - "9000:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3030:3000"
    volumes:
      - grafana-storage-blacklight:/var/lib/grafana

  text-embeddings-inference:
    image: ghcr.io/huggingface/text-embeddings-inference:1.5
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities: ["gpu"]
              device_ids: ["7"]
    environment:
      HF_API_TOKEN: <secret>
      MODEL_ID: jinaai/jina-embeddings-v2-base-en
    volumes:
      - /ephemeral/huggingface:/root/.cache/huggingface
    ports:
      - "8080:80"
    restart: always

volumes:
  grafana-storage-blacklight:
  prometheus-data-blacklight:
