model_list:
  - model_name: NousResearch/Hermes-3-Llama-3.1-8B
    litellm_params:
      model: openai/NousResearch/Hermes-3-Llama-3.1-8B
      api_base: http://vllm-0-hermes:8000/v1

litellm_settings:
  callbacks:
    - "prometheus"