apiVersion: v1
kind: Secret
metadata:
    name: env-secrets-p2p
    namespace: local-ai
type: Opaque
stringData:
    DEBUG: ENC[AES256_GCM,data:rUyhgg==,iv:jcocbukx0myPbUbfFhetdhTBWLcUF8rlVqoua+FXOwM=,tag:tHBa0yxFKH11KcvoCKhFKQ==,type:str]
    TOKEN: ENC[AES256_GCM,data:+UqCBxCHca8ugSnAIc1rnCEXTs5g5I0qoF+9BmgRrubwUyzm0TY8MqnvE3XGzbgIIhOPbdu+5Cb0M9jk3NjqPogfok2pUZjW7guFJHSDZJphKjgR6AbmrbLdXPYOnr3y92CYJ6zGL6A0OFTY3HuDbLyqhLH0A95But+yKuRlHJs44sQrJv72l97OoOvxJcfZsj0oL1dlR84mmJ4lBU4WEcnuPdMMTx88UKAYIpkvJ0FIWdWTj06Zs/IBWsgGH6E+AvLyZW6tU5OYFrifDW4YNq8nvE+GXrKdk1mAV1qpyZ1Vu+QoLyhXx09U/gT3LC1FhUEn6AxFrc77MIVbq4O//RqANVqlmGAqc8sUAnePm7UaqR0S8vC3izuiIeoRDYQJlMXCmklzG66vguwEs8gvjojxuOTYbpBZB13AB23jyd/Wm7iOIOyYDNmpYA/Kd5nxoDaqLnTwE5KqEO55YzKE+vCqtcDo4+FMOdeIHFSyj8GcbHsQ9iYnRXtoHCl2ivvKpibUjhvsHOC/L3emY5jSj0zF+9VTLiwzYTaG6UHVjkFOsMS53DFjRjmUQmiOX8ZGwie6R/rcXZ712kixmW2nJTbgPf087fJ2KAQFh2qV88n/ys0Vz0aAHnx0xUUXdXFSX/LUS0YjUZKW04fpDZr7NSTeaKh/xipQ,iv:2FMw5HjXS3mjE8ezxniFfliKHMHPGAxWYNFTvrTFkWE=,tag:oXNs3GJFAIKLtlcle5l7sQ==,type:str]
    P2P: ENC[AES256_GCM,data:Uc430w==,iv:iM/FGk0Hnuail/orzk4rn24reGl6XlYG0oNKOusdmlQ=,tag:CdDiJPYCJWR6JMSWnOfFbQ==,type:str]
    LOCALAI_FEDERATED: ENC[AES256_GCM,data:r8WXEw==,iv:TobUH/ny8tT6p9XsgUhVdim0Qi2koN7WbGeNgPEl388=,tag:Njt/l2mpBVI1me/wQfM5ig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2p37dr88vg6lk49gkk0qf9paw3w2tr5vdr25acz2p2lu90qj4hseutrwe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUzc5b1ZsdFFCNGdUU2M4
            TlFsOUZ1QjVxd25PbFpLa1UxNTJIbmZMSkVBCkNkazJLTnVKclMzVmpYWXZlZFl0
            dUVxTllveEY1TENzM3FvK1Z6R3JvRlUKLS0tIEdkNDdwelVCOFV1Q1VaWEhaNkww
            UE5WdHNuMVNNRDE3dWl0QmxmVDJucHcKcNHAh3C93SB5QeD7lbzHDD1mHjT8LsLW
            31db1W1nDBPl3lHxF07g0Yy0RSp52u20C08Sw8bNOioLyu03uxizKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T09:48:25Z"
    mac: ENC[AES256_GCM,data:00ZuYAzJVBJWvqKFhSBpAFOUk+3q0JihDN0qnR40poB4ZMy7Uz0eI6iR2fYnIrDSgjjg6BXLIUXoxFEWE4aNuVv7CEHPfsE2wQmRA84WAP2mgTVZi7Wji/Q6kf6J506rKluwF43ZvlJ/xXijGH2Du6C2x2UNoM37b2ZHGZEbF8U=,iv:BfXvio8xQ3orD43R+I8jh5/h4aKcb9QFZOhTS571cE0=,tag:7Q/5sG5XLQZwe392AXzWXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
