apiVersion: v1
kind: Secret
metadata:
    name: env-secrets-p2p
    namespace: local-ai
type: Opaque
stringData:
    DEBUG: ENC[AES256_GCM,data:Md6I8w==,iv:CrroMROrXbF6fKeb5EjIm8zMHl0qKl3TwGRiZFV7va8=,tag:sxl9fykNJI/C1YekLTdNgA==,type:str]
    TOKEN: ENC[AES256_GCM,data:TithD+LxaePnEa+G0iXFg91YYj/UCiXULT/ObVg1MytsYaz8PiDsPUHi5Q4T6dO2oxANTq/7qEbmQuhmq1Tb2CdUrJkiMSyyYvQAbv1HYD0hB0oP7v+4/s+MhI+pEOGgTvmgmFvPsO3spAg2/HPUGE9r/4CYD9ShjDzM5AtM+Wzt7qFv+0Ok+k4u3lsjVNs+8oDGBVUgOGcPhCq+4v7/C2tC7rmr9ZiFzDmxKOjLBMmDcg/FDDFyGWTvSckmq+iO7xQ5SvT6njwR1XUXmd8sRCQBYhdf6Hi15M9vy0kaWYh3dzKr737kQpZDQ/IYWHc1YEqFvVsDvLanCz99PrzYxieywzd14Dj4L8uToiI55JPEbSUzGx2cZR70UUorWprsu1AViThEXYvQKrc/0KcvFYBdKcHv4R2ApbxLKsN+dlGFTcGjWjs6T8s6V6rNdIzqkRH7R0stCWEPHEJC87BtMUgLhGA3sw5iJwfn2F1/oBtefyDxpEj9XJg1QrwybgT6HPZHsElxzzZbYI5Qpy0B8VNmAK3dSt98JCqfHJfmUq0nhcpTaf/DIZUQjhKN3EgKGRuQJ3+tpFgEbIpAt054nCdos4rJoqWhu1ym5ly8g4MISBOrHoR5UAmOsPi2KS+xCbSOwlkYE8zYFsDVw6F/dVzJ6BZNT+zM,iv:InaqaKteYUAGnNFuoNV+xOA9bu5EKc1b26qxUWEkDik=,tag:/lVCatd8I6MPFjpe+b871w==,type:str]
    P2P: ENC[AES256_GCM,data:WwF0+g==,iv:wFE8rpvqLTgj21eKCj9Obgn+tBxR/Gf2A4CrrpEIl9E=,tag:dlZ+5pNWQjrLk27VXxrUIw==,type:str]
    LOCALAI_FEDERATED: ENC[AES256_GCM,data:hVgfHw==,iv:1GjXofbMRtH5fkpa5h52Cc+7YrDe1s0C926scCl+UfM=,tag:wvtrJ0hUXuBLbUdmnuhnoQ==,type:str]
    API_KEY: ENC[AES256_GCM,data:tfKNagjx/HFYkYiM,iv:Mye5etYFOdzjWi9oGyLXYSUxl/ts1F74u5MqQ+u5ZP0=,tag:VtZzW6IFDDOZykkN3FiTGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l2p37dr88vg6lk49gkk0qf9paw3w2tr5vdr25acz2p2lu90qj4hseutrwe
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKWk1laUtzTll4ZklFaVhy
            d3BtcmtZbURQbWU4dXV2ZEtZbmFNbzg5bzE4CkF4TDNmWm9Xcld0Q2d5TGJ3U2p6
            VHl0a2Yvc1l5cnJ6bXZMaVBETHJ4WTQKLS0tIDJ0QlBtOXo3Nis5NC9aVlQyMFZx
            WmdacFh5Vkd2MDlzRG4xMGJXcThOVlUKmn0BeQ1D6HEve6uj3iulLUOKYw6oq/+K
            0DeDIG9Nkt1WTKrxVinJCqix5VweiBe0z9J2CwIkMeKGn0b65ZQABQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-25T11:02:36Z"
    mac: ENC[AES256_GCM,data:pCwQ3z4VuA+PI7GGTET6xo5coyj5s4Hln7WS76ckNfB3OhvNZCO/R2fm6sVASjQR0XV8Fg3W+93Uf40TBB0R0RBb4cj264x8Ixeh84wRMWvzC5NYUdOqhb9d8PHR2VFZ4GX2dv8iUtl5qMh4+oHagchG6BbHEZ10bX7hgPfUI0M=,iv:XdXu+pBFPPR0mL5r0PgN7XWr3VXpOhJ/wROpc8KQSFs=,tag:Ff6XbURMNtJP++2fpqNbEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
